### PR TITLE
[CALCITE-892] Implement SortJoinTransposeRule

### PR DESCRIPTION
**Pull request by jcamachor**

### CODE REVIEW

**Comment by julianhyde** [comment]
Does this rule work if you remove the check for duplicate sorts? In volcano planner the rule will be fired many more times than it needs to be - and will still generate duplicate sorts, which will then be removed by the canonization check.

Can you add a negative test to make sure that limit is not erroneously pushed through inner join? It could be in join.oq.

The rule could in principle fire for full join, but I can see that is not very important.

I would use com.google.common.base.Objects.equals() to test fetch and offset in sortEquals because null-safe equality is such a common pattern.

**Comment by jcamachor** [comment]
@julianhyde , thanks for the comments.

1. If I remove the check for duplicate sorts, the rule was firing forever in the HepPlanner tests. In order to avoid that, you could put SortMergeRule in the same group. Thus, the discussion is between 1) creating a rule that is valid on its own, or 2) one that has dependencies with some other rules. I guess I prefer option 1), what's your take?

2. testSortJoinTranspose3 is already a negative test. I will add another negative one with a sort on the inner input.

3. For full join, I'm wondering about the implications of possibly having nulls in the sorting columns? Probably it is safe to push it for full join iff Sort consists of a "naked" limit? I'll think further on it, and update the rule accordingly before we commit it.

4. I update the pull request to use com.google.common.base.Objects.equals().

**Comment by julianhyde** [comment]
Re 1. I prefer (1) also but I wouldn't do it by making the rule look for particular types of RelNode. Nor do I want the rule to behave differently in different engines. It's a hard problem that we haven't solved yet but my suspicion is that metadata is the solution. If we can look at a RelNode - without knowing its type - and know that it will not produce more than 10 rows, then we know we don't need to apply limit(10). Similarly, metadata for uniqueness can prevent us from pushing aggregates too many times.

Suppose you ran SortJoinTransposeRule and FilterSortTransposeRule in the same Hep program. It would repeatedly push a sort through the join, then through the underlying filter. Your strategy of looking for Sort on the inputs would fail, and the program would loop. Therefore I think we need a more robust way to find out whether a rule has been fired, and the answer is metadata - because metadata has a monotonicity property.

That said I think implementing a new kind of metadata is hard, and until https://issues.apache.org/jira/browse/CALCITE-794 is fixed if we lean hard on metadata it will bite us.

Re 2. I missed that case. I still think it's useful to add something to join.oq. Then we get to see whether these plans actually work.

Re 3. I can see how full join would cause problems if you had 'order by deptno nulls first limit 3', and limiting the input would cause false-positive nulls to appear. I think the right answer is a comment that we haven't figured out full join yet.

Re 4. Great.

**Comment by jinfengni** [comment]
Comments:

1. In the rule patten specification, why do you specify the join left / right child?  
I think in onMatch() method, you could get the left/right child from the join node directly, in stead of from RelOptRuleCall. 

2. For Left/right outer join,  if sort does not have collation, then seems we could remove the sort on top of join; the sort pushed into either left or right side will ensure we get exactly the # of rows we want.

**Comment by julianhyde** [comment]
Counter-example to 2:

```sql
select * from emp left join dept using (deptno) limit 3
```

and consider that emp and dept each have 5 rows with deptno = 10. The left join ensures that there is *at least* one dept per emp but it does not ensure that there is *at most* one. Your proposed rewrite to

```sql
select *
from (select * from emp limit 3)
join (select * from dept limit 3) using (deptno)
```

would return 9 rows for deptno = 10.

**Comment by jinfengni** [comment]
For comment 2: You are right.  We could not remove Sort on top of Join.

**Comment by jcamachor** [comment]
Thanks for your comments.

@jinfengni , the only reason to specify them is that I want to get the class of the RelNode, and I would not like to use e.g. a cast to HepRelVertex to get the RelNode, as this would make the rule incompatible with Volcano planner.

@julianhyde , I have been working on a version of the rule that relies uniquely on MD providers. 
The rule checks the RowCount in order to push the limit or not.
I see a problem with this approach. Assume we push Limit(x) on the left input of the join. The input to the pushed Limit(x) has y rows, and y<x, the number of rows returned would be y. This would lead to the rule firing infinitely (at least with the HepPlanner).
Further, RowCount might not give you the exact number of rows e.g. some joins are based on a estimation, which I guess could also lead to infinite firing.
What's your take on this? Seeing this, I think we original rule might not be such a bad idea.

**Comment by jcamachor** [comment]
@julianhyde , new commit relies on MD providers instead of casting. Could you check it again?

I added the test to join.oq and the rule does not apply. The reason is that in Enumerable, Limit and Sort are different operators. I have left the test and a comment on why it does not apply.

**Pull request closed without merging**
