### PR TITLE
[CALCITE-695] Ensure the SINGLE_VALUE function would not be added when t...

### PR DESCRIPTION
**Pull request by hsuanyi**
Passed the unit test; Add one test case;

### CODE REVIEW

**Comment by julianhyde** [comment]
I don't think it would do the right thing on this query:

```sql
select deptno
from EMP
where deptno > (select min(deptno) * 2 + 10 from EMP group by gender)
```

or this:

```sql
select deptno
from EMP
where deptno > (values 10)
```

In your javadoc can you explain what you mean by "scalar"?

**Comment by julianhyde** [comment]
Or this:

```sql
select deptno
from EMP
where deptno > (select deptno * 2 + 10 from EMP order by deptno limit 1)
```

**Comment by hsuanyi** [comment]
First of all, in the javadoc, scalar refers to a single value. For example, 1 is while [1, 2, 3] is not.

For query 1, the subquery will return a non-scalar. So it is reasonable for the plan to contain a single value function like below, right? (notice because there is no "gender" this column in the table, I substituted it with "empno" in your original query.)

LogicalProject(DEPTNO=[$7])
  LogicalFilter(condition=[>($7, $9)])
    LogicalJoin(condition=[true], joinType=[left])
      LogicalTableScan(table=[[CATALOG, SALES, EMP]])
      LogicalAggregate(group=[{}], agg#0=[SINGLE_VALUE($0)])
        LogicalProject(EXPR$0=[+(*($1, 2), 10)])
          LogicalAggregate(group=[{0}], agg#0=[MIN($1)])
            LogicalProject(EMPNO=[$0], DEPTNO=[$7])
              LogicalTableScan(table=[[CATALOG, SALES, EMP]])

**Comment by hsuanyi** [comment]
For query 2, you are right. The current patch is not able to respond properly. I already had a fix.

For query 3, it is the LIMIT which makes the subquery return a scalar. I am working on it now.

**Comment by julianhyde** [comment]
While you are working on the fix, please think carefully. Your first patch added a feature but introduced an obvious bug. If you are not 100% safe to remove the SINGLE_VALUE function in a particular query you should not do it.

**Comment by julianhyde** [comment]
Sorry to quibble, but a list with one element is not scalar. See http://en.wikipedia.org/wiki/Scalar

**Pull request closed without merging**
