### PR TITLE
[CALCITE-886]: Fix Sql validation error when group by clause has a sy…

### PR DESCRIPTION
**Pull request by jinfengni**
…stem function without parentheses.

### CODE REVIEW

**Comment by julianhyde** [comment]
Try this instead: https://github.com/julianhyde/incubator-calcite/tree/886-group-by-system-function.

**Comment by jinfengni** [comment]
Did you run the unit test JdbcTest.testRunAgg()?

Actually, initially I tried the same code as you did, and it regressed in testRunAgg().  

Here is the part of the failed stack trace:
> Caused by: java.lang.UnsupportedOperationException: class org.apache.calcite.sql.SqlNodeList: 
> 	at org.apache.calcite.util.Util.needToImplement(Util.java:920)
> 	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:4199)

**Comment by julianhyde** [comment]
You're right. I guess GROUPING SETS isn't an expression (it doesn't have a type). I think the fix is for validateGroupClause to call validate on calls to GROUPING SETS, CUBE, ROLLUP and validateExpr on everything else. Please see my branch.

**Comment by jinfengni** [comment]
It looks good. This should solve the problem for now. Thanks!

As a second thought, if only SqlIdentifier has different handling for validate() and validateExpr(), the other SqlNode itself does not have difference, will it make sense to 1) remove validateExpr() from SqlNode interface, 2) SqlIdentifier will internally call validateExpr() for validate() call, 3) all the callers call SqlNode.validate()?

**Comment by julianhyde** [comment]
I seem to recall a problem with USING, e.g. `select * from emp join dept using (deptno)`. Here you are validating deptno as an identifier, not as an expression. So it helps to pass in the context, i.e. what you want the node to be.

**Pull request closed without merging**
