### PR TITLE
Lazily create exception only when it needs to be thrown

### PR DESCRIPTION
**Pull request by mprudhom**
Exceptions are expensive to create, so don't create a RuntimeException() unless we are actually going to throw something.

### CODE REVIEW

**Comment by julianhyde** [comment]
How about using Util.FoundOne.NULL, which is static?

**Comment by mprudhom** [comment]
Sounds good to me. I'll update the patch.

**Comment by julianhyde** [comment]
I've merged it to my https://github.com/julianhyde/incubator-calcite/tree/new-master branch. The pull request will get closed when I merge to apache master, after the release.

**Comment by julianhyde** [comment]
Thanks for the pull request!

**Pull request closed without merging**
