### PR TITLE
[CALCITE-895] Make pushPredicateIntoCase work when Case-When is under…

### PR DESCRIPTION
**Pull request by hsuanyi**
… OR, AND operators

### CODE REVIEW

**Comment by hsuanyi** [comment]
Have a more general implementation. :)

**Comment by julianhyde** [comment]
I meant make the whole thing a shuttle, and use the shuttle's support for scanning arg lists and rebuilding calls, like this: https://github.com/julianhyde/incubator-calcite/tree/895-case-push

**Comment by julianhyde** [comment]
@hsuanyi If you don't have any objections, I'll check in the two commits in https://github.com/julianhyde/incubator-calcite/tree/895-case-push.

**Comment by hsuanyi** [comment]
Oh. I read your patch earlier. It looks good to me.

**Pull request closed without merging**
